services:
  frontend:
    build: ./public
    ports:
      - 3000:3000
    depends_on:
      - backend
  backend:
    build: ./server
    ports:
      - 5000:5000
    depends_on:
      - db
  db:
    image: mongo:7.5
    expose:
      - 27017
    volumes:
      dbdata:/data/db
volumes:
  dbdata: