services:
  frontend:
    build: ./public
    ports:
      - 3000:3000
    depends_on:
      - backend
  backend:
    build: ./server
    expose:
      - 3000
    environment:
      - PORT=3000
      - MONGO_URL=mongodb://db:27017/chat
    depends_on:
      - db
  db:
    image: mongo:7.0
    expose:
      - 27017
    volumes:
      - dbdata:/data/db
volumes:
  dbdata: