services:
  frontend:
    build:
      context: ./public
      dockerfile: Dockerfile
    ports:
      - 3000:3000

    volumes:
      - ./public:/app
      - /app/node_modules
    command: ["npm", "start"]
  backend:
    volumes:
      - ./server:/app
      - /app/node_modules