FROM node:16-alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN npm install --only=production

COPY . .

RUN npm run build

FROM nginx:1.26.3-alpine-slim

COPY --from=builder /app/build /usr/share/nginx/html

EXPOSE 3000

CMD ["nginx","-g","daemon off;"]